### ISSUE TITLE
Implement Ajax for Youtube API to get instructional video

### ISSUE THREAD

**Issue by torre-matthew** [torre-matthew/Git-Lit#11]
As Greta, I need an easy way to get a recipe video for making a cocktail so that I can follow along when making my cocktails at home.

- [x] Research the YouTube API
- [x] Prepare ajax call for querying the youtube API with search params from form input.
- [x] Prepare iframe to dynamically update with video. Determine id or class that will be used to display video.
- [x] Parse data from Ajax and display one video on page.

**Comment by PReijerkerk** [comment]
In my testing of the iframe implementation it appears certain videos on youtube are unable to be played in an iframe. I believe this is mostly affecting music copyrights so we may need to find a way to implement functionality to grab another video if the first call does not function.
